[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
machine = { path = "../machine" }
accelerator = { path = "../accelerator" }
tokio = { workspace = true, features = ["rt", "macros"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
serde_json = { workspace = true }
crossterm = "0.28"
